# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-05 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gplay_id', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djgpp.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=5)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djgpp.Permission')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='permissions',
            field=models.ManyToManyField(to='djgpp.Permission'),
        ),
    ]
