# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 10:24
from __future__ import unicode_literals

# django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djgpp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='description_ru',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='text_ru',
            field=models.TextField(null=True),
        ),
    ]
